### ISSUE TITLE
Adicionar botão do Whatsapp flutuante

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/site#109]

**Comment by kaiofelipejs** [comment]
Pretendo puxar essa issue. Dúvidas:
- Esse botão ficará em todas as páginas? 
- Qual o número que manda? Alguma mensagem padrão?

**Comment by gabrnunes** [comment]
@kaiofelipejs, sim, todas as páginas. Pode ser só um círculo com o logo do Whatsapp.

Pode mandar pro meu celular mesmo, a mensagem não precisa pode deixar em branco.

**Comment by kaiofelipejs** [comment]
@gabrnunes beleza, já vou puxar o dev aqui
