### ISSUE TITLE
Ajustar código para trazer informações do DatoCMS apenas de um determinado evento

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/site#124]
Como agora são 3 sites para 3 eventos em um só, precisamos criar um novo filtro para pegar os dados apenas de um determinado evento.

- Logo dos patrocinadores no rodapé
- Programação
- Palestrantes

**Comment by Markkop** [comment]
Já tem algum identificado no banco de dados pra identificar o conteúdo de cada evento?

**Comment by gabrnunes** [comment]
Feito!
