### ISSUE TITLE
Criar área para login com Sympla

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/site#125]
O código já tá meio pronto no site do SH*FT Festival, só tem que adaptar pro padrão da Codecon.

**Comment by Markkop** [comment]
https://github.com/gabrnunes/shuft-site/blob/release/pages/api/auth.ts
https://github.com/gabrnunes/shuft-site/blob/release/components/login.tsx

deixar aqui pra referencia

**Comment by Markkop** [comment]
A gente vai usar o prisma mesmo?

**Comment by gabrnunes** [comment]
Não, @Markkop, respondi lá no outro PR. É pra adaptar pro Sequelize que já usamos no site
