### ISSUE TITLE
Criar componente que mostra últimas pessoas que geraram tickets

### ISSUE THREAD

**Issue by gabrnunes** [codecon-dev/site#134]
https://www.figma.com/file/5RnzQJbGoOB9CQXQt0ZvAe/%5BCodecon-23%5D-Site?node-id=2108-1439&t=tpkSl9wHwrcNMxNw-4

**Comment by Markkop** [comment]
De qual API podemos pegar esses dados?

**Comment by gabrnunes** [comment]
Na verdade vai ser do próprio banco de dados. A ideia é que quem gerar o ticket compartilhável apareça aqui, sacou?

**Comment by gabrnunes** [comment]
Feito!
