### ISSUE TITLE
[Conteúdo] Dados dos palestrantes

### ISSUE THREAD

**Issue by paulacarol** [codecon-dev/site#19]
Formulário e respostas : https://docs.google.com/forms/d/15rAcUIhZaHji9BmOu-DBYDrGPkiA4FTHQEbuG_VkbOk/edit
em inglês: https://docs.google.com/forms/d/1FGUwvD5uNw0l2UpHvFHJwrz5dx7UtazdQu3f_V5GYbE/edit

**Palestras**
- [x] Cassidy
- [x] Elton Minetto
- [x] Erika Heidi
- [x] Glenn Vanderburg
- [x] Loiane Groner
- [x] Lissa Ferreira - C4P
- [x] Leticia 'levxyca' - C4P
- [x] Vitor Norton - C4P
- [x] André Dutra - C4P
- [x] Gabriel Galdino Gomes - C4P

**Painéis**
- [x] Avelino
- [x] Bruce (Desvcansados)
- [x] Bruna Vaz (Devscansados)
- [x] Bruno Rocha
- [x] Camilo
- [x] Eduardo Matos
- [x] Fernando Cézar
- [x] Fernando Daciuk
- [x] Gabriel de Biasi (Trybe)
- [x] Giovana (painel com Fernando Cézar)
- [x] Glaucia Lemos
- [x] Hanna Camelo
- [x] Isabella - Mage
- [x] Jeferson (Linuxtips)
- [x] Jéssica Temporal
- [x] Joás
- [x] Kizzy Terra
- [x] Leila Welich
- [x] Lucas Teles (a55)
- [x] Lucas Santos
- [x] Mila Laranjeira
- [x] Neto Marin (Google)
- [x] Otavio Santana
- [x] Pachi Codes
- [x] Paulo Gonçalves
- [x] Roberta Arcoverde
- [x] Robson Amorim (Lambda3)
- [x] Thiago Ghisi
- [x] Vanessa Sant Anna
- [x] Willian Molinari
- [x] Zeno Rocha (pediu pra usar do site dele)

**Hosts**
- [x] Fernando Cézar (também está na lista de palestrantes)
- [x] Fernanda Bernardo
- [x] Morganna
- [x] Pachi Codes (também está na lista de palestrantes)
- [x] Cynthia Zanoni
- [x] Priscila Aranha
- [x] Pedro Castilho
- [x] Gabs

**Workshops**
- [x] David - Mage
- [ ] Eduardo Mendes (Dunossauro)
- [x] Erick - Mage
- [x] Flávio Losada
- [x] Letícia Garcez
- [x] Marcel dos Santos
- [x] Renan - Mage
- [x] Vinícius Campitelli
- [x] Vedovelli
- [x]  Hotmart (patrocinado): Paulo Vasconcelos

**Palestras patrocinadas**
- [x] X-Team: Atekkita (Karolina)
- [ ] X-Team: Nicolas
- [x] X-Team: Filipe Degrazia
- [x] X-Team: host à definir Arthur?
- [x]  Alura: Guilherme [host]
- [x] Alura: Moni Hillman
- [x] Alura: Antônio Evaldo
- [x]  Grupo Boticário: William Moraes
- [x]  Jetbrains: Paulo Gúbio
- [x]  OnlyOffice: Edson C. da Silva
- [x]  Revelo: Mauro Murari
- [x] Revelo: Rodrigo Alencar
- [x] Revelo: Tadeu Zagallo
- [x] Revelo: Ana Neri
- [x]  TOTVS: John Costa
- [x]  Tractian: João
- [x]  Twilio: Gabriel Bolzi de Souza

**Comment by gabrnunes** [comment]
@jnassula pode jogar as imagens aqui dai pra ficar organizadinho. :)
