### ISSUE TITLE
[CONTEÚDO] Avatar dos Palestrantes

### ISSUE THREAD

**Issue by jnassula** [codecon-dev/site#41]
**Palestras**

- [x] Cassidy Williams
- [x] Elton Minetto
- [x] Erika Heidi
- [x] Glenn Vanderburg
- [x] Loiane Groner
- [x]  Lissa Ferreira - C4P
- [x]  Leticia 'levxyca' - C4P
- [x]  Vitor Norton - C4P
- [x]  André Dutra - C4P
- [x]  Gabriel Galdino Gomes - C4P

**Painéis**

- [x] Avelino
- [x] Bruce (Desvcansados)
- [x] Bruna Vaz (Devscansados)
- [x] Bruno Rocha
- [x] Camilo
- [x] Eduardo Matos
- [x] Fernando Cézar
- [x] Fernando Daciuk
- [x] Gabriel de Biasi (Trybe)
- [x]  Giovana (painel com Fernando Cézar)
- [x] Glaucia Lemos
- [x] Hanna Camelo
- [x] Isabella - Mage
- [x] Jeferson (Linuxtips)
- [x] Jéssica Temporal
- [x] Joás
- [x] Kizzy Terra
- [x] Leila Welich
- [x] Lucas Teles (a55)
- [x] Lucas Santos
- [x] Mila Laranjeira
- [x] Neto Marin (Google)
- [x] Otavio Santana
- [x] Pachi Codes
- [x] Paulo Gonçalves
- [x] Roberta Arcoverde
- [x] Robson Amorim (Lambda3)
- [x] Thiago Ghisi
- [x] Vanessa Sant Anna
- [x] Willian Molinari
- [x] Zeno Rocha

**Hosts**

- [x] Fernando Cézar (também está na lista de palestrantes)
- [x]  Fernanda Bernardo
- [x]  Morganna
- [x]  Pachi Codes (também está na lista de palestrantes)
- [x]  Cynthia Zanoni
- [x]  Priscila Aranha
- [ ]  Código Falado?
- [x]  Gabs

**Workshops**

- [x] David - Mage
- [x]  Eduardo Mendes (Dunossauro)
- [x] Erick - Mage
- [x] Flávio Losada
- [x] Letícia Garcez
- [x] Marcel dos Santos
- [ ]  Renan - Mage
- [x] Vinícius Campitelli
- [x] Vedovelli
- [ ]  Hotmart (patrocinado): definir

Palestras patrocinadas

- [x]  X-Team: Atekkita (Karolina)
- [ ]  X-Team: Nicolas
- [ ]  Alura:
- [x]  Grupo Boticário: William Moraes
- [ ]  Jetbrains:
- [x]  OnlyOffice: Edson C. da Silva
- [x]  Revelo: Mauro Murari
- [x]  Revelo: Rodrigo Alencar
- [x]  Revelo: Tadeu Zagallo
- [x]  Revelo: Ana Neri
- [x]  TOTVS: John Costa
- [ ]  Tractian:
- [x]  Twilio: Gabriel Bolzi de Souza

**Comment by jnassula** [comment]
Elton Minetto
https://dynamic-assets.gather.town/sprite/avatar-C0ykfrlDx7AkQsLyLcNS-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-l24zd4C0cjM4q3KJ8ZIo-T5QZUtaGSeZFoK2VuMhd-lLr5aJclDm4oQ6TvSZsk.png

**Comment by jnassula** [comment]
Erika Heidi
https://dynamic-assets.gather.town/sprite/avatar-6Ma2YvjiQrl68ByWFqHK-C0ykfrlDx7AkQsLyLcNS-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-E5FYHFBMmdkixM7TOTZf-XJNUjgXpXV6EUQBaXP9F.png

**Comment by jnassula** [comment]
Glenn Vanderburg
https://dynamic-assets.gather.town/sprite/avatar-KqTqvfFl86GbTsCRv5AY-djP7vOTvaY3mablnskJr-Thh1O95hOZKq4yyTmVQD-wnUCBsCtQalRTcuPnEHb-q6dBhWMIgzU4gRNCnEol-RnPGrbCAK84rwkCpUDEy.png

**Comment by jnassula** [comment]
Loiane Groner
https://dynamic-assets.gather.town/sprite/avatar-UgGYbirxIeUZKOIyMH5i-KqTqvfFl86GbTsCRv5AY-z3y0nUr4eDNKtW90WqEl-Thh1O95hOZKq4yyTmVQD-2ucAdSDMlbV50FLNye5c-UZIm4Q68HkfqPhthjM5v.png

**Comment by jnassula** [comment]
Cassidy Williams
https://dynamic-assets.gather.town/sprite/avatar-QoPCoTqKhAur8mRn2DqA-9m3qVgHfBsdmFN5EuagD-7zJ0QmraQS9GAldP9hrk-Thh1O95hOZKq4yyTmVQD-X6OKlB3GQ8UvKDfutznE-lfOdc20ozxM1lW3Z8z1l-YZ9Fru7tckppHt694D4E.png

**Comment by jnassula** [comment]
Thiago Avelino
https://dynamic-assets.gather.town/sprite/avatar-8hCSfYIK6RvpToNgMJNB-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-l24zd4C0cjM4q3KJ8ZIo-WaMM8u1pW2GyKfBCGCZp-gOLxmc6a6kx5l0AM6k1f.png

**Comment by jnassula** [comment]
Kizzy Terra
https://dynamic-assets.gather.town/sprite/avatar-dmY7DnvYU0Ytw0fN6Wf7-55WIiGhFapYltADFT8Ai-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-iaTHvtflads9t61RLhAV-9wX09bszi3s3PGiSXiA8.png

**Comment by jnassula** [comment]
Pachi Codes
https://dynamic-assets.gather.town/sprite/avatar-Gu68ae9LBq7i7copNCe5-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-P5xxrLs0ZSa2YyUAjVrU-efEN5bwnQR62abguxuEW.png

**Comment by jnassula** [comment]
Roberta Arcoverde
https://dynamic-assets.gather.town/sprite/avatar-QoPCoTqKhAur8mRn2DqA-R7cVd1GzcUu4CbnXHAWe-7zJ0QmraQS9GAldP9hrk-QspYaieLR4jBqhdChkNT-eM8UxV9RpxWElxz76xr8-lfOdc20ozxM1lW3Z8z1l.png

**Comment by jnassula** [comment]
Bruno Rocha
https://dynamic-assets.gather.town/sprite/avatar-8hCSfYIK6RvpToNgMJNB-7zJ0QmraQS9GAldP9hrk-k42rDCI5m8J53KHJPSaK-mybVhQINQ63B0OpfQHc9-7SqoR7WLWniXx6OMI9Gv-KKesnLgezuBq3bfs4cGf-o6W4ZrvUKaFKul3pIch8.png

**Comment by jnassula** [comment]
Jefferson (LinuxTips)
https://dynamic-assets.gather.town/sprite/avatar-9m3qVgHfBsdmFN5EuagD-6AczIj4OgrICPerAqTzg-k42rDCI5m8J53KHJPSaK-SpaJhR8veURviWgQpB7t-7SqoR7WLWniXx6OMI9Gv-R735EZLUSIEtjLumGQeb-br6zFmYqB16GF9Qo5pUt.png

**Comment by paulacarol** [comment]
> Bruno Rocha https://dynamic-assets.gather.town/sprite/avatar-8hCSfYIK6RvpToNgMJNB-7zJ0QmraQS9GAldP9hrk-k42rDCI5m8J53KHJPSaK-mybVhQINQ63B0OpfQHc9-7SqoR7WLWniXx6OMI9Gv-KKesnLgezuBq3bfs4cGf-o6W4ZrvUKaFKul3pIch8.png

@jnassula dá pra fazer o Bruno Rocha de chapéu vermelho? Da Red Hat que ele sempre usa

**Comment by jnassula** [comment]
Vinícius Campitelli
https://dynamic-assets.gather.town/sprite/avatar-KqTqvfFl86GbTsCRv5AY-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-aCUhdZ1UkjfaY4P7VqGM-MTObvArFAWBkntXPLllC-7SqoR7WLWniXx6OMI9Gv-E5IkamZ7e9t4RZhoY0fH.png

**Comment by jnassula** [comment]
Vanessa Sant Anna
https://dynamic-assets.gather.town/sprite/avatar-KqTqvfFl86GbTsCRv5AY-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-iXKY550J4xwIEz29zPNM-BfxPTrFWzLVLK3sBRCic-7SqoR7WLWniXx6OMI9Gv-c1FXqZcd6ESfdVgt7C6C.png

**Comment by jnassula** [comment]
Willian Molinari
https://dynamic-assets.gather.town/sprite/avatar-egQLKXLotk1sj0mfi8TT-N2qcVD4nmKx648zARK1N-Thh1O95hOZKq4yyTmVQD-wnUCBsCtQalRTcuPnEHb-GyCB3foS6YVP5hp5Ielg-f1qhlWxcrliFbNFjaHVV-R735EZLUSIEtjLumGQeb.png

**Comment by jnassula** [comment]
Jessica Temporal 
https://dynamic-assets.gather.town/sprite/avatar-B3EejNWxR5NrBbL8V4iY-8hCSfYIK6RvpToNgMJNB-N2qcVD4nmKx648zARK1N-Thh1O95hOZKq4yyTmVQD-6Uexv3WANbVms3zQPQbj-v5NAUThjqq76E5SzFVZo-ehpsOrhJ4TzIWWc0KyuE.png

**Comment by jnassula** [comment]
Gabriel de Biasi
https://dynamic-assets.gather.town/sprite/avatar-C0ykfrlDx7AkQsLyLcNS-N2qcVD4nmKx648zARK1N-Thh1O95hOZKq4yyTmVQD-OFqilKEk9zLy3fsWOjRE-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by jnassula** [comment]
Paulo Gonçalves
https://dynamic-assets.gather.town/sprite/avatar-7n6yHxeSyqpxh2pXG7GB-C0ykfrlDx7AkQsLyLcNS-N2qcVD4nmKx648zARK1N-Thh1O95hOZKq4yyTmVQD-i0VaEF9JwMDxFserSIVS-GNYl0IGr7gOLakOOET9N.png

**Comment by jnassula** [comment]
Leticia Garcez
https://dynamic-assets.gather.town/sprite/avatar-C0ykfrlDx7AkQsLyLcNS-vxJn6CFs7Kz7IKYzxTcV-Thh1O95hOZKq4yyTmVQD-Aszf9VIUXnnJruZq8gpU-MeDrxvi5jrXMzqiScgij.png

**Comment by jnassula** [comment]
Glaucia Lemos
https://dynamic-assets.gather.town/sprite/avatar-UJ9KVWvcrNJovp09UZhA-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-b3n1QY36iUMT0BVd8pbv-xecnPDxwLrAWxjCS0OeO-J4dXGafWtTB0nvYkJ2EP-6IHqeijtAIy66lqUI7X2.png

**Comment by jnassula** [comment]
Camilo 
https://dynamic-assets.gather.town/sprite/avatar-dmY7DnvYU0Ytw0fN6Wf7-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-GAIbG8MSb2SCWNI3dtPX-kdWQ017WyLrPtAY17EBo-9wX09bszi3s3PGiSXiA8.png

**Comment by jnassula** [comment]
Eduardo Matos
https://dynamic-assets.gather.town/sprite/avatar-dmY7DnvYU0Ytw0fN6Wf7-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-l24zd4C0cjM4q3KJ8ZIo-AuPVTvNWsRwUs9sDiUtL-9wX09bszi3s3PGiSXiA8.png

**Comment by jnassula** [comment]
Robson Amorim
https://dynamic-assets.gather.town/sprite/avatar-C0ykfrlDx7AkQsLyLcNS-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-6XPy9PYbzGcSlJLNEmMx-bG2pb3yxMbOQbQLAbhv2-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by jnassula** [comment]
Fernando Daciuk
https://dynamic-assets.gather.town/sprite/avatar-C0ykfrlDx7AkQsLyLcNS-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-l24zd4C0cjM4q3KJ8ZIo-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by jnassula** [comment]
Lucas Santos
https://dynamic-assets.gather.town/sprite/avatar-C0ykfrlDx7AkQsLyLcNS-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-fgLJCRdImOOXUf2MnJ7L-7SqoR7WLWniXx6OMI9Gv-o6W4ZrvUKaFKul3pIch8.png

**Comment by jnassula** [comment]
Bruce (DevsCansados)
https://dynamic-assets.gather.town/sprite/avatar-C0ykfrlDx7AkQsLyLcNS-N2qcVD4nmKx648zARK1N-Thh1O95hOZKq4yyTmVQD-iqMdnwOFPe8qRM3Y2STl-7SqoR7WLWniXx6OMI9Gv-KKesnLgezuBq3bfs4cGf-z904S8BOdMixJwa5C8sF-qZtqN5w3RHZndyS8JQSz.png

**Comment by jnassula** [comment]
Bruna Vaz
https://dynamic-assets.gather.town/sprite/avatar-QoPCoTqKhAur8mRn2DqA-KqTqvfFl86GbTsCRv5AY-N2qcVD4nmKx648zARK1N-Thh1O95hOZKq4yyTmVQD-4jEd3bP4jVtBLQJnW3w9-lfOdc20ozxM1lW3Z8z1l.png

**Comment by jnassula** [comment]
Hanna Camelo
https://dynamic-assets.gather.town/sprite/avatar-NIhmPnxq01YH1GVxGUYj-KqTqvfFl86GbTsCRv5AY-Lx0Zpepm3KMUYFYvdNJ1-Thh1O95hOZKq4yyTmVQD-qqlvtfrQWfVKgjwvx9vQ-ERiUHW2XGyy6uTtxux4K-qL1IwgtWIbGaxRMM0CR9-8Bz7AxFH8VaXGMAcQWrj.png

**Comment by paulacarol** [comment]
> @paulacarol eu posso seguir por essa lista de imagens que vc mandou! Essa esta atualizada?

@jnassula sim, lá estão todos que se cadastraram. Mas ainda falta bastante. Se acabar da lista e tiver com tempo livre hahaha, daí você olha na lista dos participantes mesmo pra ir adiantando o avatar dos outros que ainda não mandaram foto

**Comment by paulacarol** [comment]
Fernando Cézar
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-9TPgr0kbF7LYaVXjPQKz-l24zd4C0cjM4q3KJ8ZIo-7SqoR7WLWniXx6OMI9Gv-K4audsHcI1YQCcSTxNnM-PiLMNHsvIdc9tBjGqSyh.png

**Comment by paulacarol** [comment]
Isabella Mage
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-5TG7J4iMJjDogRgauCpQ-qqfhZU2seiRlUzMOmnVf-vOoPqt0950xOO1NFYpaP-BfxPTrFWzLVLK3sBRCic-VI71mSDX3bChLFmAgMDu.png

**Comment by paulacarol** [comment]
Joás
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-7LSNXrRHjUD2SSFeR0gk-aCUhdZ1UkjfaY4P7VqGM-K4audsHcI1YQCcSTxNnM-PiLMNHsvIdc9tBjGqSyh.png

**Comment by paulacarol** [comment]
Lucas Teles
https://dynamic-assets.gather.town/sprite/avatar-dQCYs4n7O99ksXuBIe33-6AczIj4OgrICPerAqTzg-HBZkShNmve5Yu91tAThz-2MqV0PAwa76NOUM8tsda-AuPVTvNWsRwUs9sDiUtL.png

**Comment by paulacarol** [comment]
Neto Marin
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-7zJ0QmraQS9GAldP9hrk-qqfhZU2seiRlUzMOmnVf-s8U59tP7deIGRHQSwUqk-R735EZLUSIEtjLumGQeb-PiLMNHsvIdc9tBjGqSyh.png

**Comment by paulacarol** [comment]
Thiago Ghisi
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-7zJ0QmraQS9GAldP9hrk-HBZkShNmve5Yu91tAThz-xvGem6ddmz7GoEOqJ9UO-EfFbUaqnGuodRgW4YycP-7SqoR7WLWniXx6OMI9Gv-AuPVTvNWsRwUs9sDiUtL-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by paulacarol** [comment]
Davi
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-djP7vOTvaY3mablnskJr-sGropwmL9Vh8DTMp8ZXS-2MqV0PAwa76NOUM8tsda-gk0HFlB9EpUM59LMEthB-q6dBhWMIgzU4gRNCnEol-gOLxmc6a6kx5l0AM6k1f.png

**Comment by paulacarol** [comment]
Erick
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-agEvFKFD4Ta3MQ09ENbU-JatX3m7gnzX3abVz3p2I-AuPVTvNWsRwUs9sDiUtL-o6W4ZrvUKaFKul3pIch8.png

**Comment by paulacarol** [comment]
Marcel
https://dynamic-assets.gather.town/sprite/avatar-dQCYs4n7O99ksXuBIe33-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-l24zd4C0cjM4q3KJ8ZIo-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by paulacarol** [comment]
Vedovelli
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-7zJ0QmraQS9GAldP9hrk-sGropwmL9Vh8DTMp8ZXS-aCUhdZ1UkjfaY4P7VqGM-gk0HFlB9EpUM59LMEthB-MVZ1jlhLnBhezQDzYoqu.png

**Comment by paulacarol** [comment]
Flávio Losada
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-7zJ0QmraQS9GAldP9hrk-sGropwmL9Vh8DTMp8ZXS-agEvFKFD4Ta3MQ09ENbU-f1qhlWxcrliFbNFjaHVV-o6W4ZrvUKaFKul3pIch8.png

**Comment by paulacarol** [comment]
Lissa
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-7LSNXrRHjUD2SSFeR0gk-o33JlMxAewI3JTPMunov-DH1j3qiEP5ViUgQZ2RXy.png

**Comment by paulacarol** [comment]
Letícia - levxyca
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-BGyTOxoTe2vPf4G272X7-sGropwmL9Vh8DTMp8ZXS-xasQhtoRYnjTmz5j6nBG-M5NIBys3WuRgG3iAHulP.png

**Comment by paulacarol** [comment]
Vitor Norton
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-l24zd4C0cjM4q3KJ8ZIo-tPuQm6pKfdxw9sz7OH21-7SqoR7WLWniXx6OMI9Gv-AuPVTvNWsRwUs9sDiUtL-jrBSq0OXj2dkknwlT682.png

**Comment by paulacarol** [comment]
André Dutra
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-djP7vOTvaY3mablnskJr-sGropwmL9Vh8DTMp8ZXS-l24zd4C0cjM4q3KJ8ZIo-K4audsHcI1YQCcSTxNnM-FHO4J7szhQwHqfJc9Roo.png

**Comment by paulacarol** [comment]
Gabriel Galdino
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-GAIbG8MSb2SCWNI3dtPX-s9BNqtWNYf319pfiXFVR-AuPVTvNWsRwUs9sDiUtL-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by paulacarol** [comment]
Giovana
https://dynamic-assets.gather.town/sprite/avatar-g7KRLFzSkDtwKFIapUR7-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-VYpo6fDw787GGWXnCgUO-eM8UxV9RpxWElxz76xr8-gk0HFlB9EpUM59LMEthB-IFrA5H8NWL6JjeQBqG0T.png

**Comment by paulacarol** [comment]
Fernanda Bernardo
https://dynamic-assets.gather.town/sprite/avatar-g7KRLFzSkDtwKFIapUR7-R7cVd1GzcUu4CbnXHAWe-vxJn6CFs7Kz7IKYzxTcV-sGropwmL9Vh8DTMp8ZXS-8T4t9Hfi2qQCjSnQo0km-gk0HFlB9EpUM59LMEthB-IFrA5H8NWL6JjeQBqG0T.png

**Comment by paulacarol** [comment]
Morganna
https://dynamic-assets.gather.town/sprite/avatar-nx6Hdm5e04VpueSFXD87-R7cVd1GzcUu4CbnXHAWe-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-l24zd4C0cjM4q3KJ8ZIo-iLNCfD8EdEsSX9yJRcfg-Me4LTUWYWOb6cqLy6ORO.png

**Comment by paulacarol** [comment]
Pachi Codes
https://dynamic-assets.gather.town/sprite/avatar-1OwbpqNuBs21tEw8J1Gk-R7cVd1GzcUu4CbnXHAWe-vxJn6CFs7Kz7IKYzxTcV-sGropwmL9Vh8DTMp8ZXS-siHqZHBKCZ2JEiNpZYwv-Cx5UkhftOGmwnC4vaV1O-JsOQRRrk5SQ5Rxxr4fFp.png

**Comment by paulacarol** [comment]
Cynthia Zanoni
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-pPyQD6Dd0IIAxWb8Okcj-VI71mSDX3bChLFmAgMDu.png

**Comment by paulacarol** [comment]
Priscila Aranha
https://dynamic-assets.gather.town/sprite/avatar-X6RqXwn4D8HkNekVGxng-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-sGropwmL9Vh8DTMp8ZXS-DTGZUSqtbi5j0TA47jjI-kvEzmB2O2r5HjHvYOsuO.png

**Comment by paulacarol** [comment]
Gabs Ferreira
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-xpK3Fk6qh2MemlexMHzE-sGropwmL9Vh8DTMp8ZXS-l24zd4C0cjM4q3KJ8ZIo-IB8RWQXWXDXnlCGA3qKE-bG2pb3yxMbOQbQLAbhv2-h37M7AxpqECaj0keJcz8.png

**Comment by paulacarol** [comment]
Eduardo - dunossauro
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-GAIbG8MSb2SCWNI3dtPX-R735EZLUSIEtjLumGQeb-gOLxmc6a6kx5l0AM6k1f.png

**Comment by paulacarol** [comment]
Atekkita
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-vxJn6CFs7Kz7IKYzxTcV-sGropwmL9Vh8DTMp8ZXS-tt6f2GNw0ABWkHiQCYqC-rri3zCmfIf4KGyIDCorI.png

**Comment by paulacarol** [comment]
Gabriel Bolzi - palestra patrocinada
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-7zJ0QmraQS9GAldP9hrk-sGropwmL9Vh8DTMp8ZXS-hYN5O0Jy97yuGHXUWuNQ-D7Bk8qHiLC9XMixzYqAf.png

**Comment by paulacarol** [comment]
John - palestra patrocinada
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-djP7vOTvaY3mablnskJr-Thh1O95hOZKq4yyTmVQD-l24zd4C0cjM4q3KJ8ZIo-o6W4ZrvUKaFKul3pIch8.png

**Comment by paulacarol** [comment]
Edson - palestra patrocinada
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-8IxYJmX9KwGUNSKpnJ5L-sGropwmL9Vh8DTMp8ZXS-J0QxbgjqIwOYz3Drqued-K4audsHcI1YQCcSTxNnM-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by paulacarol** [comment]
Rodrigo Alencar - palestra patrocinada
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-7zJ0QmraQS9GAldP9hrk-sGropwmL9Vh8DTMp8ZXS-l24zd4C0cjM4q3KJ8ZIo-xecnPDxwLrAWxjCS0OeO-CgjGnJ2FTTfWiE3tf7Uj.png

**Comment by paulacarol** [comment]
Tadeu Zagallo
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-fHjFBTcz5GBjEoPJsRcf-sGropwmL9Vh8DTMp8ZXS-aCUhdZ1UkjfaY4P7VqGM-K4audsHcI1YQCcSTxNnM-CgjGnJ2FTTfWiE3tf7Uj-Hqqwvfr7zQCiVS5QknmA.png

**Comment by paulacarol** [comment]
Ana Neri
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-Thh1O95hOZKq4yyTmVQD-4tdlhMwOSoLNsOou2X7w-ajuL49i7C1GPb3SSzdGE.png

**Comment by paulacarol** [comment]
Mauro Murari - palestra patrocinada
https://dynamic-assets.gather.town/sprite/avatar-R7cVd1GzcUu4CbnXHAWe-6AczIj4OgrICPerAqTzg-HBZkShNmve5Yu91tAThz-bc5LTqO9n3K0SQ1GMOt0-K4audsHcI1YQCcSTxNnM-PiLMNHsvIdc9tBjGqSyh.png

**Comment by gabrnunes** [comment]
> 

@paulacarol pq vc fez o Neto Marin com barba?
